# Generated by Django 5.1.7 on 2026-03-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_platformsetting_organization_subscription_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_condition',
            field=models.CharField(blank=True, choices=[('monotributista', 'Monotributista'), ('responsable_inscripto', 'Responsable Inscripto'), ('exento', 'Exento'), ('consumidor_final', 'Consumidor Final'), ('otro', 'Otro')], max_length=40),
        ),
    ]
