# Generated by Django 5.1.7 on 2026-03-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_organization_address_organization_tax_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fiscal_document_issued',
            field=models.BooleanField(default=False),
        ),
    ]
