# Generated by Django 5.1.7 on 2026-03-10 03:00

import studio.modules.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_studioclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=studio.modules.core.models.default_enabled_modules),
        ),
    ]
