# Generated by Django 5.1.7 on 2026-03-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_organization_enabled_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='electronic_billing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='mercadolibre_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
