# Generated by Django 5.1.7 on 2026-03-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_organization_electronic_billing_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='activity_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='afip_environment',
            field=models.CharField(blank=True, choices=[('homologacion', 'Homologacion'), ('produccion', 'Produccion')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='afip_pos_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='organization',
            name='afip_pos_billing_system',
            field=models.CharField(blank=True, choices=[('wsfe', 'Webservice WSFE'), ('comprobantes_en_linea', 'Comprobantes en linea')], max_length=40),
        ),
        migrations.AddField(
            model_name='organization',
            name='afip_pos_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='fiscal_apartment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='fiscal_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='fiscal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='fiscal_floor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='fiscal_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='fiscal_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='fiscal_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='fiscal_street',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='fiscal_street_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='iibb_condition',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='organization',
            name='iibb_jurisdiction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='iibb_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='organization',
            name='iibb_type',
            field=models.CharField(blank=True, choices=[('local', 'Contribuyente local'), ('convenio_multilateral', 'Convenio multilateral'), ('exento', 'Exento')], max_length=40),
        ),
        migrations.AddField(
            model_name='organization',
            name='main_activity_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='wsaa_certificate_alias',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
