# Generated by Django 5.1.7 on 2026-03-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_organization_activity_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.TextField(blank=True),
        ),
    ]
