# Generated by Django 5.1.7 on 2026-03-10 23:23

import studio.modules.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='weekly_hours',
            field=models.JSONField(blank=True, default=studio.modules.core.models.default_weekly_hours),
        ),
    ]
