# Generated by Django 5.1.7 on 2026-03-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0012_establishment_weekly_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='blocked_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='blocked_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
