# Generated by Django 5.1.7 on 2026-03-11 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_room_blocked_from_room_blocked_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ARS', max_length=8)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('classes_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='studio.organization')),
            ],
            options={
                'ordering': ('organization_id', 'id'),
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('class_single', 'Pago de clase'), ('membership', 'Pago de membresia')], max_length=20)),
                ('provider', models.CharField(choices=[('mercadopago', 'MercadoPago'), ('manual', 'Manual')], default='mercadopago', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('canceled', 'Cancelado'), ('refunded', 'Reintegrado')], default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('payer_name', models.CharField(blank=True, max_length=120)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ARS', max_length=8)),
                ('external_reference', models.CharField(blank=True, max_length=80, unique=True)),
                ('provider_payment_id', models.CharField(blank=True, max_length=80)),
                ('checkout_url', models.URLField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('membership_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='studio.membershipplan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='studio.organization')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='studio.student')),
                ('studio_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='studio.studioclass')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('emitted', 'Emitida'), ('error', 'Error')], default='draft', max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=40)),
                ('voucher_type', models.CharField(default='FACTURA_C', max_length=20)),
                ('point_of_sale', models.PositiveIntegerField(default=1)),
                ('cae', models.CharField(blank=True, max_length=20)),
                ('cae_expires_on', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('arca_request', models.JSONField(blank=True, default=dict)),
                ('arca_response', models.JSONField(blank=True, default=dict)),
                ('emitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='studio.organization')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='studio.payment')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
    ]
