# Generated by Django 5.1.7 on 2026-03-11 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_membershipplan_payment_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Usuario y contrasena'), ('google', 'Google SSO'), ('facebook', 'Facebook SSO')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned_establishment', 'Assigned Establishment'), ('joined_marketplace', 'Joined Marketplace'), ('manual_note', 'Manual Note')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('organization', 'user'), name='unique_student_profile_per_org_user'),
        ),
    ]
