# Generated by Django 5.1.7 on 2026-03-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0015_student_auth_provider_student_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='brand_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='company_registry_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(blank=True, default='ARS', max_length=8),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_domain',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='fiscal_country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='organization',
            name='fiscal_street_line2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organization',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
