# Generated by Django 5.1.7 on 2026-03-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0020_platformsubscriptionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('class_single', 'Pago de clase'), ('membership', 'Pago de membresia'), ('platform_subscription', 'Suscripcion de plataforma')], max_length=32),
        ),
    ]
