# Generated by Django 5.1.7 on 2026-03-16 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0022_instructorprofile_and_enabled_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('compensation_scheme', models.CharField(choices=[('hourly', 'Pago por hora'), ('monthly', 'Sueldo mensual'), ('per_class', 'Pago por clase'), ('mixed', 'Esquema mixto')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='ARS', max_length=8)),
                ('month_classes', models.PositiveIntegerField(default=0)),
                ('month_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('completed_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='studio.instructorprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_settlements', to='studio.organization')),
            ],
            options={
                'ordering': ('-period_year', '-period_month', 'organization_id', 'instructor_profile_id'),
                'unique_together': {('organization', 'instructor_profile', 'period_year', 'period_month')},
            },
        ),
    ]
