# Generated by Django 6.0.2 on 2026-03-17 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_ai_assistant_module(apps, schema_editor):
    Organization = apps.get_model("studio", "Organization")
    PlatformSubscriptionPlan = apps.get_model("studio", "PlatformSubscriptionPlan")
    module_key = "ia_asistente"

    for organization in Organization.objects.all():
        modules = list(organization.enabled_modules or [])
        if module_key not in modules:
            modules.append(module_key)
            organization.enabled_modules = modules
            organization.save(update_fields=["enabled_modules"])

    for plan in PlatformSubscriptionPlan.objects.all():
        modules = list(plan.included_modules or [])
        if module_key not in modules:
            modules.append(module_key)
            plan.included_modules = modules
            plan.save(update_fields=["included_modules"])


def remove_ai_assistant_module(apps, schema_editor):
    Organization = apps.get_model("studio", "Organization")
    PlatformSubscriptionPlan = apps.get_model("studio", "PlatformSubscriptionPlan")
    module_key = "ia_asistente"

    for organization in Organization.objects.all():
        modules = [module for module in (organization.enabled_modules or []) if module != module_key]
        organization.enabled_modules = modules
        organization.save(update_fields=["enabled_modules"])

    for plan in PlatformSubscriptionPlan.objects.all():
        modules = [module for module in (plan.included_modules or []) if module != module_key]
        plan.included_modules = modules
        plan.save(update_fields=["included_modules"])


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0024_socialaccount_socialcampaign_socialpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('ollama', 'Ollama / local')], default='openai', max_length=20)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('api_key', models.TextField(blank=True)),
                ('base_url', models.URLField(blank=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.2, max_digits=4)),
                ('max_context_items', models.PositiveIntegerField(default=8)),
                ('include_classes_context', models.BooleanField(default=True)),
                ('include_students_context', models.BooleanField(default=True)),
                ('include_finance_context', models.BooleanField(default=True)),
                ('include_instructors_context', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistant_config', to='studio.organization')),
            ],
            options={
                'ordering': ('organization_id',),
            },
        ),
        migrations.CreateModel(
            name='AIAssistantInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('ollama', 'Ollama / local')], max_length=20)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistant_interactions', to='studio.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assistant_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.RunPython(add_ai_assistant_module, remove_ai_assistant_module),
    ]
