# Generated by Django 6.0.2 on 2026-02-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='includes_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('turno', 'Turno'), ('clase_grupal', 'Clase grupal'), ('tratamiento', 'Tratamiento')], default='turno', max_length=24),
        ),
    ]
