# Generated by Django 6.0.2 on 2026-02-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_service_capacity_service_includes_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('turno', 'Turno'), ('clase_grupal', 'Clase grupal'), ('tratamiento', 'Tratamiento'), ('alquiler_cancha', 'Alquiler de cancha')], default='turno', max_length=24),
        ),
    ]
