# Generated by Django 6.0.2 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_alter_service_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
