# Generated by Django 6.0.2 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="court_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
