# Generated by Django 6.0.2 on 2026-02-18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_appointment_court_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("court_name", models.CharField(blank=True, default="", max_length=120)),
                ("start_dt", models.DateTimeField()),
                ("end_dt", models.DateTimeField()),
                ("reason", models.CharField(blank=True, default="", max_length=220)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_slots_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.tenant")),
            ],
            options={
                "ordering": ["-start_dt"],
            },
        ),
        migrations.AddIndex(
            model_name="blockedslot",
            index=models.Index(fields=["tenant", "start_dt"], name="booking_blo_tenant__4b7363_idx"),
        ),
        migrations.AddIndex(
            model_name="blockedslot",
            index=models.Index(fields=["tenant", "court_name"], name="booking_blo_tenant__6ca806_idx"),
        ),
    ]
