# Generated by Django 6.0.2 on 2026-02-13 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('core', '0001_initial'),
        ('crm', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desired_date', models.DateField()),
                ('time_window_start', models.TimeField(blank=True, null=True)),
                ('time_window_end', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=12)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlists', to='marketplace.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-desired_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='crm.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('waitlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='waitlist.waitlist')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
                'unique_together': {('waitlist', 'client')},
            },
        ),
        migrations.CreateModel(
            name='WaitlistOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='offered', max_length=12)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_offers', to='booking.appointment')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='waitlist.waitlistentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
