# Generated by Django 6.0.2 on 2026-02-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_and_tenant_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('pilates', 'Pilates'), ('estetica', 'Estetica'), ('peluqueria', 'Peluqueria'), ('mixto', 'Mixto')], default='mixto', max_length=24),
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD'), ('EUR', 'EUR')], default='ARS', max_length=8),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_zone',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='company',
            name='revenue_model',
            field=models.CharField(choices=[('turnos', 'Turnos'), ('suscripciones', 'Suscripciones'), ('mixto', 'Mixto')], default='mixto', max_length=24),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_rate_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cancellation_policy',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='tenant',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tenant',
            name='establishment_type',
            field=models.CharField(choices=[('sala', 'Sala'), ('cabina', 'Cabina'), ('puesto', 'Puesto')], default='sala', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='opening_hours',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tolerance_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
