# Generated by Django 6.0.2 on 2026-02-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_business_type_company_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allow_local_payments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='allow_online_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cancellation_penalty_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='prepay_required',
            field=models.BooleanField(default=False),
        ),
    ]
