# Generated by Django 6.0.2 on 2026-02-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_allow_local_payments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('pilates', 'Pilates'), ('estetica', 'Estetica'), ('peluqueria', 'Peluqueria'), ('futbol', 'Futbol'), ('padel', 'Padel'), ('tenis', 'Tenis'), ('canchas', 'Canchas deportivas'), ('mixto', 'Mixto')], default='mixto', max_length=24),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='establishment_type',
            field=models.CharField(choices=[('sala', 'Sala'), ('cabina', 'Cabina'), ('puesto', 'Puesto'), ('cancha', 'Cancha')], default='sala', max_length=20),
        ),
    ]
