# Generated by Django 6.0.2 on 2026-02-16

from django.db import migrations, models


def copy_revenue_model_to_tenants(apps, _schema_editor):
    Company = apps.get_model("core", "Company")
    Tenant = apps.get_model("core", "Tenant")

    for company in Company.objects.all().iterator():
        company_revenue = getattr(company, "revenue_model", "mixto") or "mixto"
        Tenant.objects.filter(company_id=company.id).update(revenue_model=company_revenue)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_company_business_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="revenue_model",
            field=models.CharField(
                choices=[
                    ("turnos", "Turnos"),
                    ("suscripciones", "Suscripciones"),
                    ("mixto", "Mixto"),
                ],
                default="mixto",
                max_length=24,
            ),
        ),
        migrations.RunPython(copy_revenue_model_to_tenants, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="company",
            name="business_type",
        ),
        migrations.RemoveField(
            model_name="company",
            name="revenue_model",
        ),
    ]
