# Generated by Django 6.0.2 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_move_revenue_model_to_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="court_config",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
