# Generated by Django 6.0.2 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_tenant_court_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="photo_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
